
export const sample_foods: any[] = [
  {
    id:'1',
    name: 'Dosa ',
    cookTime: '5-10',
    price: 45,
    favorite: false,
    origins: ['India'],
    stars: 4.5,
    imageUrl: 'https://th.bing.com/th/id/OIP.apQfIcEq5a6wqVxWwX6GcgHaE8?pid=ImgDet&rs=1',
    tags: ['Breakfast','Lunch', 'All Menus'],
  },
  {
    id:'2',
    name: 'Idli Sambhar',
    price: 50,
    cookTime: '20-30',
    favorite: true,
    origins: ['India'],
    stars: 4.7,
    imageUrl: 'https://udupi-recipes.com/wp-content/uploads/2017/05/barnyard-millet-idli-goodness-of-millet-1-500x500.jpg',
    tags: ['Breakfast', 'All Menus'],
  },
  {
    id:'3',
    name: 'Dal kichadi',
    price: 50,
    cookTime: '30-45',
    favorite: false,
    origins: ['India'],
    stars: 4.1,
    imageUrl: 'https://www.indianhealthyrecipes.com/wp-content/uploads/2014/09/ven-pongal-recipe.jpg',
    tags: ['Breakfast', 'All Menus'],
  },
  {
    id:'4',
    name: 'Veg Biryani',
    price: 120,
    cookTime: '30-45',
    favorite: true,
    origins: ['India'],
    stars: 5,
    imageUrl: 'https://th.bing.com/th/id/R.4050c1338d937e86561f15a8ad500e33?rik=u1b5VYHPpZ0%2bgg&riu=http%3a%2f%2fwww.zeelskitchen.com%2fwp-content%2fuploads%2f2015%2f07%2fVegtable_Biryani.jpg&ehk=YyC6fyyAqPOxwoCcfh5%2bagrdHkkH9OFNIm8hx5pChY0%3d&risl=&pid=ImgRaw&r=0',
    tags: ['Lunch', 'Dinner', 'All Menus'],
  },
  {
    id:'5',
    name: 'Tomato Soup',
    price: 90,
    cookTime: '40-50',
    favorite: false,
    origins: ['India', 'asia'],
    stars: 4.0,
    imageUrl: 'https://th.bing.com/th/id/OIP.D5kqfBPg-OXEj1tZ_ofr2wHaE8?pid=ImgDet&rs=1',
    tags: ['Soup', 'All Menus'],
  },
  {
    id:'6',
    name: 'North Indian Thali',
    price: 145,
    cookTime: '40-50',
    favorite: false,
    origins: ['India'],
    stars: 4.0,
    imageUrl: 'https://2.bp.blogspot.com/-5GLXsoV1Azc/VuGeRgqoBlI/AAAAAAAADbU/9g2SmBJYCas/s1600/North-Indian-Thali.jpg',
    tags: ['Dinner', 'Lunch', 'All Menus'],
  },
  {
    id:'7',
    name: 'French fries',
    price: 80,
    cookTime: '40-50',
    favorite: false,
    origins: ['Chinese'],
    stars: 4.0,
    imageUrl: 'https://th.bing.com/th/id/OIP.T96-l_gUGQYf8e0GFOosngHaHm?pid=ImgDet&rs=1',
    tags: ['Fry', 'All Menus'],
  },
  {
    id:'8',
    name: 'Veg Soup',
    price: 90,
    cookTime: '40-50',
    favorite: false,
    origins: ['India', 'asia'],
    stars: 4.0,
    imageUrl: 'https://th.bing.com/th/id/OIP.1kqeUMJiLpox2IePrQixdwHaFj?pid=ImgDet&rs=1',
    tags: [ 'Soup', 'All Menus'],
  },
  {
    id:'9',
    name: 'Veg Manchurian',
    price: 90,
    cookTime: '20-30',
    favorite: false,
    origins: ['Chinese'],
    stars: 4.0,
    imageUrl: 'https://th.bing.com/th/id/R.b57797fb70d3289daa6adc5908008b6d?rik=iWFZ4hYo8DXCKg&riu=http%3a%2f%2fwww.foodvedam.com%2fwp-content%2fuploads%2f2017%2f10%2fVeg-Manchurian1.jpg&ehk=g3h42zDoVlHKhtRFqiyborWOYd%2bGt4PXoefj3Q2F4s4%3d&risl=&pid=ImgRaw&r=0&sres=1&sresct=1',
    tags: ['FastFood', 'All Menus'],
  },
  {
    id:'10',
    name: 'Noodles',
    price: 90,
    cookTime: '20-30',
    favorite: false,
    origins: ['Chinese'],
    stars: 4.0,
    imageUrl: 'https://th.bing.com/th/id/R.525a6d12fc52a7dde653ff5d3cffb053?rik=0SRch8AmgRspGA&riu=http%3a%2f%2fyesofcorsa.com%2fwp-content%2fuploads%2f2015%2f08%2f3050_noodles.jpg&ehk=LJCOo68qTdGV%2bDP9TnpsT5JfyxT7TV6Bq2lSPxKCf%2fQ%3d&risl=&pid=ImgRaw&r=0',
    tags: ['FastFood', 'All Menus'],
  },
  {
    id:'11',
    name: 'Fried Rice',
    price: 90,
    cookTime: '20-30',
    favorite: false,
    origins: ['Chinese'],
    stars: 4.8,
    imageUrl: 'https://live.staticflickr.com/4039/5122884598_f48ae5cd97_b.jpg',
    tags: ['FastFood', 'All Menus'],
  },
  {
    id:'12',
    name: 'Deserts',
    price: 90,
    favorite: false,
    stars: 4.8,
    imageUrl: 'https://th.bing.com/th/id/OIP.QB91OuWRG8aPrNMFQnZA1gHaEo?pid=ImgDet&rs=1',
    tags: ['Desert', 'All Menus']
  },
]

export const sample_tags:any[] = [
  { name: 'All Menus', count: 12 },
  { name: 'FastFood', count: 3 },
  { name: 'Lunch', count: 3 },
  { name: 'Breakfast', count: 3 },
  { name: 'Fry', count: 1 },
  { name: 'Soup', count: 2 },
  { name: 'Desert', count: 1 }
]

export const sample_users: any[] = [
  {
    name: "Gagan J N",
    email: "gagan@gmail.com",
    password: "gagan",
    address: "Banglore",
    isAdmin: true,
  },
  {
    name: "Gayatri",
    email: "gayatri@gmail.com",
    password: "gayatri",
    address: "Hyderabad",
    isAdmin: false,
  },
  {
    name: "Maneesh",
    email: "maneesh@gmail.com",
    password: "maneesh",
    address: "Hyderabad",
    isAdmin: false,
  },
  {
    name: "Chandra",
    email: "chandra@gmail.com",
    password: "chandra",
    address: "Hyderabad",
    isAdmin: false,
  },
];